apiVersion: api.cel.example.com/v1
kind: Mypod
metadata:
  labels:
    app.kubernetes.io/name: cel-demo
    app.kubernetes.io/managed-by: kustomize
  name: mypod-sample
spec:
  # TODO(user): Add fields here
